name: Deploy Malala Api

on:
  push:
    branches:
      - main
    paths:
      - 'malala-api/**'

jobs:
  deploy-malala-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: composer install --no-dev

      - name: Deploy Malala API
        run: |
          php artisan migrate --force && php artisan up
